= RHDP default showroom theme
// Settings:
:experimental:
:hide-uri-scheme:
// Project URLs:
:url-project: https://github.com/rhpds/rhdp_showroom_theme
:url-ci-pipelines: {url-project}/pipelines
:img-ci-status: {url-project}/badges/master/pipeline.svg
// External URLs:
:url-antora: https://antora.org
:url-antora-docs: https://docs.antora.org
:url-git: https://git-scm.com
:url-git-dl: {url-git}/downloads
:url-gulp: http://gulpjs.com
:url-opendevise: https://opendevise.com
:url-nodejs: https://nodejs.org
:url-nvm: https://github.com/creationix/nvm
:url-nvm-install: {url-nvm}#installation
:url-source-maps: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map


== Use the Default UI

If you want to simply use the default UI for your Antora-generated site, add the following UI configuration to your playbook:

[source,yaml]
----
ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/raw/main/releases/download/v0.0.1/ui-bundle.zip
    snapshot: true
----

NOTE: The `snapshot` flag tells Antora to fetch the UI when the `--fetch` command-line flag is present.
This setting is required because updates to the UI bundle are pushed to the same URL.
If the URL were to be unique, this setting would not be required.

Read on to learn how to customize the default UI for your own documentation.

== How to use the theme

=== Add Additional Links

You can add links to external content in the convenient "Links" drop-down on the upper-right of the UI.

../content/antora.yml
[source,yaml]
----
asciidoc:
  attributes:
    page-links:
    - url: https://redhat.com
      text: Red Hat
    - url: https://www.redhat.com/en/summit
      text: Summit
----

=== Add a User menu entry

Similar to the external links, you can have a new menu entry with the name of the user

../content/antora.yml
[source,yaml]
----
asciidoc:
  attributes:
    user: 'User X'
----